name: IsletopiaSkyWar
version: ${project.version}
main: com.molean.isletopia.isletopiaskywar.IsletopiaSkyWar
api-version: 1.17
commands:
  sdebug: { }
  edebug: { }
  tdebug: { }
  team: { }
load: STARTUP