name: IsletopiaSkyWar
version: ${project.version}
main: com.molean.isletopia.isletopiaskywar.IsletopiaSkyWar
api-version: 1.17
commands:
  sdebug:
    permission: isletopia
  edebug:
    permission: isletopia
  tdebug:
    permission: isletopia
  team: { }

load: STARTUP